Diam 92
bcgov/JAG-JPIDP pull request #525
Opened 2024-04-22 22:33 UTC by SujithaChandragupthanAG

# Description

This PR includes the following proposed change(s):

- {List all the changes, if possible add the jira ticket #}

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Helm charts?

- [ ] Yes
- [ ] No

If Yes: Has Helm been updated accordingly?

- [ ] Yes
- [ ] No

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes

2024-04-22 23:00 UTC, leewrigh requested changes

2024-04-22 23:00 UTC, leewrigh commented on .github/workflows/build-push-approvalflow.yml
> +          sed -i "s/apitag: .*/apitag: dev-${{ steps.short_sha.outputs.SHORT_SHA }} # Image Updated on $DATETIME/" frontend/values.yaml
The path for each service will need to change - e.g. approvalflow will need to update the values.yaml under the approvalflow folder rather than frontend

2024-04-23 15:02 UTC, SujithaChandragupthanAG commented on .github/workflows/build-push-approvalflow.yml
> +          sed -i "s/apitag: .*/apitag: dev-${{ steps.short_sha.outputs.SHORT_SHA }} # Image Updated on $DATETIME/" frontend/values.yaml
The path for each service has been updated. Kindly review and share your comments.

2024-04-23 16:00 UTC, leewrigh approved these changes

2024-04-23 16:00 UTC, merged